### ISSUE TITLE
Log in with cookies?

### ISSUE THREAD

**Issue by dnm13** [Tenpi/pixiv.ts#19]
Can I log in with cookies (PHPSESSID) that I could get from pixiv page?

I tried using `Pixiv.refreshLogin()` with my cookies as the parameter and it doesn't work.
Can we improve this method to support login with cookies too?

**Comment by Tenpi** [comment]
The Pixiv API and website are separate, to be specific when you are using this you are logging into `https://app-api.pixiv.net/` not `https://www.pixiv.net/`.

To log into the API currently you can only use your refresh token, which cannot be gotten from your cookies. Follow this guide on how to get your refresh token and use that to login:
https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362
