### ISSUE TITLE
Search Illust Page

### ISSUE THREAD

**Issue by akanami-shinzo** [Tenpi/pixiv.ts#21]
Search Illusts only shows the first page and 30 results

**Comment by Tenpi** [comment]
Subsequent page results are stored in the `nextURL` property and you can use the utility `util.multiCall()` to iterate automatically until the provided limit of results, or all results if no limit is provided

Example:
```ts
let limit = 100
let illusts = await pixiv.search.illusts({word: "query"})
if (pixiv.search.nextURL) illusts = [...illusts, ...await pixiv.util.multiCall({next_url: pixiv.search.nextURL, illusts}, limit)]
```
