### ISSUE TITLE
await util.downloadIllust does not work

### ISSUE THREAD

**Issue by dgudim** [Tenpi/pixiv.ts#31]
Basically I want to download images to a folder and after they are downloaded, convert and move them to another folder.

This does not work and crashed with `[Error: VipsJpeg: Premature end of input file]` because files didn't finish downloading yet

```ts
const illust = await client.illust.get(url);
const img_dir = "./downloaded";
await sendToChannel(channel, `📥 Downloading from pixiv`);


let images = walk(img_dir);

for (const image of images) {
    const new_file_name = getFileName(image);
    const new_file_path = await getFilePath(new_file_name, channel);
    if(new_file_path) {
    await processAndSaveImage(fs.createReadStream(image));
    fs.unlinkSync(image);
}

```

However, if i add `sleep(5000);` before `walk(img_dir);` it works, which means that `await client.util.downloadIllust(illust, img_dir, "original");` does not actually wait untill all images are saved

**Comment by Tenpi** [comment]
It waits correctly, as seen with this simple check. Debugging issues with your code is not of my concern.

```ts
await pixiv.util.downloadIllust(illusts[0], "./downloads", "original")
const files = fs.readdirSync(path.join(__dirname, "../downloads")).map((p) => path.join(__dirname, "../downloads", p))
console.log(fs.readFileSync(files[0]))

<Buffer 00 00 00 01 42 75 64 31 00 00 20 00 00 00 08 00 00 00 
20 00 00 00 10 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 08 00 00 00 ... 10194 more bytes>
```
