### ISSUE TITLE
Third time's the charm. await client.util.downloadIllust does not wait

### ISSUE THREAD

**Issue by dgudim** [Tenpi/pixiv.ts#33]
I literally just took your example with the hashes and it doesn't work.

```ts
await client.util.downloadIllust(url, "./downloads", "original");

const files = fs.readdirSync(path.join(__dirname, "../downloads")).map((p) => {
    return path.join(__dirname, "../downloads", p)
})
const hash = crypto.createHash("md5").update(fs.readFileSync(files[0])).digest("hex")
console.log(hash);
for(let i = 1; i < 5; i++) {
    setTimeout(() => {
        const hash2 = crypto.createHash("md5").update(fs.readFileSync(files[0])).digest("hex")
        console.log(hash2)
        console.log(hash === hash2)
    }, i * 1000)
}
```
the output is as follows

```
2a96de86c25cd98a85c89debfed3fe4e
7cbe45c3c4fdf5cf4c3cd0ae78ee1a1b -- after a second
false
aad8d30495ccc35463511dc27bd0e52d -- after 2 seconds
false
f56fb56448ec3df54eb0986a81ce0554 -- after 3 seconds
false
4528e847c998aa0617f56412ca11a624 -- after 4 seconds
false
25cd98a8aaaad7f56412e4e2a96de86c -- after 5 seconds
false
```
and also, i get this
![](https://i.imgur.com/rcDeBLQ.png")

please dont close the damn issue, let's discuss this, I just don't see where this is my problem

here is the post I tried it on: `https://www.pixiv.net/en/artworks/98079929`

It contains 3 images by the way

**Comment by Tenpi** [comment]
The _multiple_ page illusts appear to resolve after downloading the first page, but update to `0.5.9`, that should fix it. If it doesn't, then go fix it yourself instead of spamming me with issues.

**Comment by dgudim** [comment]
Man, it's your library, not mine, why are you being toxic, I am just trying to use your great library. Anyway, updated to 0.5.9 and the issue is fixed.
